name       : qt6-languageserver
version    : 6.3.0
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtlanguageserver-everywhere-src-6.3.0.tar.xz : 70aad8f7060e1e0c40365cb3f0f5f572643a5390f59d8e5a327df6fc0a9eeeaa
license    : GPL-3.0-or-later
component  : desktop.qt
summary    : An implementation of the Language Server Protocol
description: |
    An implementation of the Language Server Protocol
builddeps  :
    - pkgconfig(Qt6Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
