name       : qt6-languageserver
version    : 6.5.1
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qtlanguageserver-everywhere-src-6.5.1.tar.xz : 99a6cc6aca124626a2085077dc7f4bb9dbb20da518df6b115056813149832bc9
license    : GPL-3.0-or-later
component  : desktop.qt
summary    : An implementation of the Language Server Protocol
description: |
    An implementation of the Language Server Protocol
builddeps  :
    - pkgconfig(Qt6Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
